name: Run Azure Login with OIDC
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Sign in via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
